"""Pull GSI videos + transcripts with NO Google login, via yt-dlp.

Because the channel's videos are unlisted (reachable by link), yt-dlp can read
their metadata and subtitles directly — no OAuth, no account access. Point this
at a playlist URL containing all the videos (or pass individual video URLs) and
it enumerates them, writes each one's info + subtitles, and assembles
``data/videos/transcripts.json``.

Transcript source per video (in order): manual subtitles, then auto-captions.
Videos with neither are listed as candidates for audio transcription.

Usage:
    python scripts/youtube_pull_ytdlp.py "<playlist-or-video-url>" ["<url2>" ...]
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from standards_rag.video import parse_standard_ids_from_title
from youtube_pull import _subs_to_text  # reuse vtt/srt -> text cleaner

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "videos" / "transcripts.json"


def run_ytdlp(urls: list[str], work: Path) -> None:
    cmd = [
        "yt-dlp", "--ignore-errors", "--skip-download",
        "--write-info-json", "--write-subs", "--write-auto-subs",
        "--sub-langs", "en.*", "--sub-format", "vtt",
        "-o", f"{work}/%(id)s.%(ext)s", *urls,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stderr[-800:])


def main() -> None:
    urls = sys.argv[1:]
    if not urls:
        raise SystemExit('Pass a playlist or video URL, e.g.\n'
                         '  python scripts/youtube_pull_ytdlp.py "https://youtube.com/playlist?list=..."')

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        print(f"Fetching metadata + subtitles for: {', '.join(urls)}\n")
        run_ytdlp(urls, work)

        entries, missing = [], []
        for info_path in sorted(work.glob("*.info.json")):
            info = json.loads(info_path.read_text(encoding="utf-8"))
            vid = info["id"]
            # yt-dlp also writes an info.json for the playlist container itself — skip it.
            if info.get("_type") == "playlist" or len(vid) != 11:
                continue
            title = info.get("title", "Untitled video")
            # prefer a manual subtitle file, else an auto-caption file
            subs = sorted(work.glob(f"{vid}*.vtt"))
            manual = [p for p in subs if "-orig" not in p.name and "auto" not in p.name]
            chosen = (manual or subs)
            transcript = _subs_to_text(chosen[0].read_text(encoding="utf-8", errors="ignore")) if chosen else ""
            standards = list(parse_standard_ids_from_title(title))
            entries.append(
                {
                    "video_id": vid,
                    "youtube_id": vid,
                    "title": title,
                    "transcript": transcript,
                    "description": info.get("description", ""),
                    "channel": info.get("channel") or info.get("uploader", ""),
                    "standards": standards,
                    "url": f"https://www.youtube.com/watch?v={vid}",
                }
            )
            if not transcript:
                missing.append(title)
            print(f"  [{'ok' if transcript else 'NO TRANSCRIPT':13}] {vid}  {title[:50]:50} standards={standards}")

        if not entries:
            raise SystemExit("\nNo videos found. Is the playlist link correct / does it contain the videos?")

        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(json.dumps(
            {"_comment": "Auto-generated by scripts/youtube_pull_ytdlp.py (no-login, via yt-dlp).",
             "videos": entries}, indent=2))
        print(f"\nWrote {len(entries)} videos -> {OUT}")
        if missing:
            print(f"\n{len(missing)} video(s) have NO transcript (need audio transcription):")
            for t in missing:
                print(f"   - {t}")


if __name__ == "__main__":
    main()
